url: 
baseurl: 

# Site settings
title: Joey Langley
email: joemagnum1@hotmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e42711
  secondary: b21001 
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Joey Langley
  pic: joey-langley-profile
  position: Designer | Developer
  social:
    - title: twitter
      url: https://twitter.com/hjlangleyjr
    - title: facebook
      url: https://www.facebook.com/Joey-Langley-116204335146651/
    - title: linkedin
      url: https://www.linkedin.com/in/joeylangley


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty